Run readme.md through grammarly
actions-runner-controller/actions-runner-controller pull request #1353
Opened 2022-04-18 21:25 UTC by VinGarcia

This PR tries to fix a few typos I found when reading the README files. I reported these on this issue: #1352

I tried to be very conservative here so I haven't fixed all the issues, but the ones I did I think are relevant.

For example, I ignored many suggestions to add commas or hyphens because these don't affect the readability.

2022-04-19 09:37 UTC, toast-gear requested changes

2022-04-19 09:37 UTC, toast-gear commented on README.md
> +A `RunnerDeployment` or `RunnerSet` can scale the number of runners between `minReplicas` and `maxReplicas` fields driven by either pull based scaling metrics or via a webhook event (see limitations
```suggestion
A `RunnerDeployment` or `RunnerSet` can scale the number of runners between `minReplicas` and `maxReplicas` fields driven by either pull based scaling metrics or via a webhook event (see limitations section of [RunnerSets](#runnersets) for caveats of this kind). Whether the autoscaling is driven from a webhook event or pull based metrics it is implemented by backing a `RunnerDeployment` or `RunnerSet` kind with a `HorizontalRunnerAutoscaler` kind.
```

2022-04-21 20:02 UTC, VinGarcia commented
@toast-gear thanks for the help, just applied your suggestion.

2022-04-22 15:57 UTC, toast-gear approved these changes
LGTM cheers pal

2022-04-22 15:58 UTC, merged