Feat/shellcheck
actions-runner-controller/actions-runner-controller pull request #1517
Opened 2022-06-09 11:28 UTC by CASABECI

Thanks for resource available

2022-06-30 06:23 UTC, Fleshgrinder requested changes
I am working on rewriting the scripts to be proper Bash, and pass all shellcheck tests. Hence, I would prefer it if this PR is not merged. For instance, the `logger.sh` script already does not exist anymore and was replaced by `logger.bash` in https://github.com/actions-runner-controller/actions-runner-controller/pull/1246. Similarly, the `startup.sh` script saw a total rewrite in https://github.com/actions-runner-controller/actions-runner-controller/pull/1454 (which was reverted in https://github.com/actions-runner-controller/actions-runner-controller/pull/1561 but actually already has a proper fix in https://github.com/actions-runner-controller/actions-runner-controller/pull/1560 so that it can be merged again).

2022-09-25 00:47 UTC, mumoshu commented on .github/workflows/runners.yml
> +           make -C runner lint-scripts
Hey @CASABECI! Thanks for a lot for your contribution.
I finally managed to revisit this PR and have some time to integrate your work into the project,
and realized that we now have an exclusion rulle for `runner/Makefile` so if we added this `lint-scripts` target to the this file, it won't get triggered when the Makefile has changed.
Probably we'd better roll a new workflow dedicated for running spellcheck... Let me try.

2022-09-25 02:55 UTC, mumoshu commented on runner/startup.sh
> +
FYI TIL that you can tell shellcheck the path to look from the scripts.
`shellcheck --source-path runner` made this mark unnecessary.

2022-11-03 04:27 UTC, mumoshu commented
＠CASABECI Hey! Sorry for the massive delay, but we finally managed to introduce shellcheck into our CI workflow and fixed many lint errors along the way. See linked pull requests for more information. Your contribution enabled me to get started with shellcheck very quickly. Thanks a lot for your work!

2022-11-03 04:27 UTC, closed without merging