chart: Remove support for extensions/v1beta1 and networking.k8s.io/v1beta1
actions-runner-controller/actions-runner-controller pull request #1632
Opened 2022-07-12 01:52 UTC by mumoshu

`networking.k8s.io/v1` has been available since v1.19.

As of today, AWS EKS supports v1.19+ and Oracle Cloud supports v1.20+. GKE and AKS supports v1.21+. The upstream Kubernetes project maintains v1.22+.
So it should be safe to remove it now.

2022-07-12 13:43 UTC, toast-gear requested changes
I noticed we reference `networking.k8s.io/v1/Ingress` in a few other places in this file

2022-07-15 01:00 UTC, mumoshu commented
@toast-gear Good catch! Fixed in 9148457

2022-07-16 13:25 UTC, toast-gear approved these changes

2022-07-17 10:42 UTC, mumoshu commented
Thanks for reviewing 🙏

2022-07-17 10:42 UTC, merged