Restructure documentation
actions-runner-controller/actions-runner-controller pull request #2114
Opened 2023-01-04 00:26 UTC by SiaraMist

2023-01-04 12:32 UTC, Link- commented on README.md
> +- [Adding ARC runners to a repository, organization, or enterprise](/docs/choosing-runner-destinations.md)
```suggestion
- [Adding ARC runners to a repository, organization, or enterprise](/docs/choosing-runner-destination.md)
```

There's a typo in the file name causing a 404

2023-01-04 12:47 UTC, Link- requested changes
LGTM, I'd love a quick 👍 from @mumoshu or @toast-gear as well

2023-01-05 01:23 UTC, mumoshu approved these changes
Looks awesome! Thank you very much for all your efforts 👍

2023-01-05 09:47 UTC, Link- approved these changes

2023-01-05 09:47 UTC, merged