Documentation corrections
actions-runner-controller/actions-runner-controller pull request #2116
Opened 2023-01-05 18:27 UTC by gabegreenwood

Several small fixes to the documentation:
- Couple of broken links on Quickstart page
- Typo in troubleshooting page (ssh should be SSD)
- Error in one of the helm commands in Quickstart: the create repo command creates a repo called `actions-runner-controller` but in the following command it is referred to simply as `actions`, which throws a "repo not found" error. Changing the repo name to `actions` fixes this and makes the second command work correctly.

2023-01-05 18:30 UTC, gabegreenwood commented on docs/quickstart.md
> +helm repo add actions https://actions-runner-controller.github.io/actions-runner-controller
The alternative to this change, in order to make this command work with the next one without the proposed change, would be to change line 65 below to:
`--wait actions-runner-controller actions-runner-controller/actions-runner-controller`

2023-01-05 20:27 UTC, SiaraMist commented
Thank you for fixing the broken links! 🙏

2023-01-26 22:44 UTC, SiaraMist commented
Thanks again for these updates @gabegreenwood! ✨ 

@Link-, from a docs perspective, this PR won't cause any conflicts with our current progress. 👍 So if your team does a technical review and approves, this is good to merge from docs!

2023-01-31 13:01 UTC, Link- requested changes
Thank you @gabegreenwood for your contribution. I'm requesting a small change before merging these fixes. Thank you

2023-01-31 13:01 UTC, Link- commented on docs/quickstart.md
> +helm repo add actions https://actions-runner-controller.github.io/actions-runner-controller
I don't see the need for this change, the project is still called `actions-runner-controller` and using that name for the installation makes sense.

2023-02-08 22:18 UTC, gabegreenwood commented on docs/quickstart.md
> +helm repo add actions https://actions-runner-controller.github.io/actions-runner-controller
Looks like the issue was corrected by updating line 65 in another PR so this change isn't necessary

2023-02-08 22:20 UTC, gabegreenwood commented
@Link- I made the change you requested, my original change was no longer necessary as the issue seems to have been corrected by changing a different line in that same file.

2023-02-21 00:19 UTC, mumoshu commented
Fixed another conflict. I believe this is good to go now!

2023-02-21 00:21 UTC, mumoshu approved these changes
Thank you so much for your contribution @gabegreenwood!

2023-02-21 00:22 UTC, TingluoHuang approved these changes

2023-02-21 18:40 UTC, Link- approved these changes

2023-02-21 18:40 UTC, merged