Helm chart react changes for the new runner image.
actions-runner-controller/actions-runner-controller pull request #2348
Opened 2023-03-01 20:18 UTC by TingluoHuang

Reaction work to https://github.com/actions/runner/pull/2469

2023-03-02 08:11 UTC, Link- requested changes

2023-03-02 08:11 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +we are making the following change to align the runner image close to the Hosted ubuntu runner.
```suggestion
We aim to provide an experience as close as possible between self-hosted and GitHub-hosted runners. To achieve this, we are making the following changes to align our self-hosted runner container image with the Ubuntu runners managed by GitHub.
```

2023-03-02 08:12 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +- We create a USER `runner(1001)` and a GROUP `docker(123)`
```suggestion
- We created a USER `runner(1001)` and a GROUP `docker(123)`
```

2023-03-02 08:12 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +- `sudo` will be installed on the image and the `runner` will be a passwordless sudoer.
```suggestion
- `sudo` has been on the image and the `runner` will be a passwordless sudoer.
```

2023-03-02 08:12 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +- The runner binary will be placed under `/home/runner/run.sh`
```suggestion
- The runner binary was placed placed under `/home/runner/run.sh`
```

2023-03-02 08:13 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +- The runner's work directory will be `/home/runner/_work`
```suggestion
- The runner's work directory is `/home/runner/_work`
```

2023-03-02 08:14 UTC, Link- commented on adrs/2022-10-17-runner-image.md
> +- The docker image user will be the `runner(1001)`
```suggestion
- The container image user will be the `runner(1001)`
```

2023-03-02 09:14 UTC, Link- reviewed
Thank you for fixing this! Left a few minor comments

2023-03-03 11:49 UTC, nikola-jokic commented on adrs/2022-10-17-runner-image.md
> +# Breaking Changes
This ADR is really outdated now... 
Should we make another one and mark this one as outdated?

2023-03-03 14:00 UTC, nikola-jokic commented on charts/gha-runner-scale-set/values.yaml
> +      command: ["/home/runner/run.sh"]
```suggestion

```
After entrypoint.sh gets merged and runne rimage is published: https://github.com/actions/actions-runner-controller/pull/2337

2023-03-09 18:37 UTC, Link- approved these changes

2023-03-09 18:41 UTC, rentziass approved these changes

2023-03-10 11:18 UTC, merged