Add status check before deserializing runner-registration response
actions-runner-controller/actions-runner-controller pull request #2699
Opened 2023-06-23 14:19 UTC by nikola-jokic

Added check similar to one in the runner making sure the status code is success

https://github.com/actions/runner/blob/9c57205c1c1cd7ada73cb08b556293ec0411f8d4/src/Runner.Listener/Configuration/ConfigurationManager.cs#L777C50-L777C50

2023-06-23 14:50 UTC, nikola-jokic commented on github/actions/testserver/server.go
> +			return
```suggestion

```

2023-07-03 08:39 UTC, Link- commented on github/actions/client.go
> +		return nil, fmt.Errorf("unexpected response from Actions service during registration call: %v", resp.StatusCode)
Are we dumping that response somewhere else? We might need to see what the service is returning in order to troubleshoot the root cause of this error

2023-07-03 08:41 UTC, Link- requested changes
Can we please add more context to the PR description so that we use it as documentation for why this change was introduced? 

1. Describe the problem
2. How this change addresses that problem

2023-07-05 15:55 UTC, Link- approved these changes
This looks good, thank you

2023-07-05 19:09 UTC, merged