feat: allow namespace overrides
actions-runner-controller/actions-runner-controller pull request #3797
Opened 2024-11-06 13:05 UTC by fernandezcuesta

2025-03-06 11:41 UTC, nikola-jokic reviewed
Can you please add tests?

2025-03-06 11:41 UTC, nikola-jokic commented on charts/gha-runner-scale-set/values.yaml
> +# Add the option to deploy in another namespace rather than .Release.Namespace.
```suggestion
# Overrides the default `.Release.Namespace` for all resources in this chart.
```

2025-03-06 11:41 UTC, nikola-jokic commented on charts/gha-runner-scale-set-controller/values.yaml
> +# Add the option to deploy in another namespace rather than .Release.Namespace.
```suggestion
# Overrides the default `.Release.Namespace` for all resources in this chart.
```

2025-03-07 10:48 UTC, fernandezcuesta commented
@nikola-jokic done

2025-03-07 11:13 UTC, nikola-jokic commented
Hey @fernandezcuesta,

Can you also resolve conflicts. Sorry, I can do it for you if you want.

2025-03-07 12:47 UTC, nikola-jokic requested changes

2025-03-07 12:47 UTC, nikola-jokic commented on charts/gha-runner-scale-set/templates/kube_mode_role.yaml
> +    {{- toYaml . | nindent 4 }}
You are missing labels and namespace here and the finalizers

2025-03-07 12:47 UTC, nikola-jokic commented on charts/gha-runner-scale-set/templates/kube_mode_serviceaccount.yaml
> +  {{- if or .Values.annotations $hasCustomResourceMeta }}
Missing the namespace

2025-03-07 12:50 UTC, fernandezcuesta commented on charts/gha-runner-scale-set/templates/kube_mode_role.yaml
> +    {{- toYaml . | nindent 4 }}
yeah sorry, I figured it out right after pushing and was fixing that

2025-03-07 12:50 UTC, fernandezcuesta commented on charts/gha-runner-scale-set/templates/kube_mode_serviceaccount.yaml
> +  {{- if or .Values.annotations $hasCustomResourceMeta }}
should be fixed

2025-03-07 13:11 UTC, nikola-jokic commented on charts/gha-runner-scale-set/tests/template_test.go
> +		if err != nil {
I'm sorry for insisting, but I don't think this is the right way to test it. 

If there is an error in yaml format, render would fail, and we would skip it. The better way to probably do it is to have `map[string]*helm.Options`. I understand it is time consuming, but we really need to properly cover these test cases so we don't introduce errors in future releases.

2025-03-07 14:06 UTC, fernandezcuesta commented on charts/gha-runner-scale-set/tests/template_test.go
> +		if err != nil {
What I saw is that this fails if:

there template is conditionally rendered (e.g. wrapped in an {{- if .Values.xxxx }})
the template invokes a helper which relies on a separate resource, but here we're deploying a single resource

I thought about rendering the whole chart as is (not template by template), then check every single resource's metadata.name and assert it matches namespaceOverride but didn't find an easy way to do it.

Sorry but I don't fully understand your suggestion about using Helm options, do you refer to inject the values that may potentially hide certain resources (as explained above, the reason to ignore them)?

2025-03-07 14:37 UTC, nikola-jokic commented on charts/gha-runner-scale-set/tests/template_test.go
> +		if err != nil {
Thank you for responding quickly and applying fixes!

2025-03-07 14:56 UTC, fernandezcuesta commented on charts/gha-runner-scale-set/tests/template_test.go
> +		if err != nil {
let me know wdyt now

2025-03-07 16:20 UTC, nikola-jokic commented on charts/gha-runner-scale-set/tests/template_test.go
> +}
```suggestion
func TestNamespaceOverride(t *testing.T) {
	t.Parallel()

	chartPath := "../../gha-runner-scale-set"

	releaseName := "test"
	releaseNamespace := "test-" + strings.ToLower(random.UniqueId())
	namespaceOverride := "test-" + strings.ToLower(random.UniqueId())

	tt := map[string]struct {
		file    string
		options *helm.Options
	}{
		"manager_role": {
			file: "manager_role.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"manager_role_binding": {
			file: "manager_role_binding.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"no_permission_serviceaccount": {
			file: "no_permission_serviceaccount.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"autoscalingrunnerset": {
			file: "autoscalingrunnerset.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"githubsecret": {
			file: "githubsecret.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"kube_mode_role": {
			file: "kube_mode_role.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"containerMode.type":                 "kubernetes",
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"kube_mode_role_binding": {
			file: "kube_mode_role_binding.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"containerMode.type":                 "kubernetes",
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
		"kube_mode_serviceaccount": {
			file: "kube_mode_serviceaccount.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":                  namespaceOverride,
					"containerMode.type":                 "kubernetes",
					"controllerServiceAccount.name":      "foo",
					"controllerServiceAccount.namespace": "bar",
					"githubConfigSecret.github_token":    "gh_token12345",
					"githubConfigUrl":                    "https://github.com",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
		},
	}

	for name, tc := range tt {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			templateFile := filepath.Join("templates", tc.file)

			output, err := helm.RenderTemplateE(t, tc.options, chartPath, releaseName, []string{templateFile})
			if err != nil {
				t.Errorf("Error rendering template %s from chart %s: %s", tc.file, chartPath, err)
			}

			type object struct {
				Metadata metav1.ObjectMeta
			}
			var renderedObject object
			helm.UnmarshalK8SYaml(t, output, &renderedObject)
			assert.Equal(t, namespaceOverride, renderedObject.Metadata.Namespace)
		})
	}
}
```

2025-03-07 16:21 UTC, nikola-jokic commented on charts/gha-runner-scale-set-controller/tests/template_test.go
> +}
```suggestion
func TestNamespaceOverride(t *testing.T) {
	t.Parallel()

	chartPath := "../../gha-runner-scale-set-controller"

	releaseName := "test"
	releaseNamespace := "test-" + strings.ToLower(random.UniqueId())
	namespaceOverride := "test-" + strings.ToLower(random.UniqueId())

	tt := map[string]struct {
		file          string
		options       *helm.Options
		wantNamespace string
	}{
		"leader_election_role": {
			file: "leader_election_role.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride": namespaceOverride,
					"replicaCount":      "2",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: namespaceOverride,
		},
		"leader_election_role_binding": {
			file: "leader_election_role_binding.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride": namespaceOverride,
					"replicaCount":      "2",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: namespaceOverride,
		},
		"manager_single_namespace_controller_role": {
			file: "manager_single_namespace_controller_role.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":          namespaceOverride,
					"flags.watchSingleNamespace": "true",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: namespaceOverride,
		},
		"manager_single_namespace_controller_role_binding": {
			file: "manager_single_namespace_controller_role_binding.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":          namespaceOverride,
					"flags.watchSingleNamespace": "true",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: namespaceOverride,
		},
		"manager_single_namespace_watch_role": {
			file: "manager_single_namespace_watch_role.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":          namespaceOverride,
					"flags.watchSingleNamespace": "target-ns",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: "target-ns",
		},
		"manager_single_namespace_watch_role_binding": {
			file: "manager_single_namespace_watch_role_binding.yaml",
			options: &helm.Options{
				Logger: logger.Discard,
				SetValues: map[string]string{
					"namespaceOverride":          namespaceOverride,
					"flags.watchSingleNamespace": "target-ns",
				},
				KubectlOptions: k8s.NewKubectlOptions("", "", releaseNamespace),
			},
			wantNamespace: "target-ns",
		},
	}

	for name, tc := range tt {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			templateFile := filepath.Join("templates", tc.file)

			output, err := helm.RenderTemplateE(t, tc.options, chartPath, releaseName, []string{templateFile})
			if err != nil {
				t.Errorf("Error rendering template %s from chart %s: %s", tc.file, chartPath, err)
			}

			type object struct {
				Metadata metav1.ObjectMeta
			}
			var renderedObject object
			helm.UnmarshalK8SYaml(t, output, &renderedObject)
			assert.Equal(t, tc.wantNamespace, renderedObject.Metadata.Namespace)
		})
	}
}
```

2025-03-07 16:21 UTC, nikola-jokic reviewed
Suggested few updates for clarity.
You need to add import for these:
```go
import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```

2025-03-07 17:16 UTC, fernandezcuesta commented on charts/gha-runner-scale-set-controller/tests/template_test.go
> +}
uhm in this case I guess we're not covering all the resources, for example the deployment is out of the scope. My point here was to add some fallback Values, and customize only those with conditions. In the case of `gha-runner-scale-set` chart, your suggestion fully makes sense and covers all resources (didn't realize that all of them had to have an entry), but in this case there're more resources which are OK with just setting `nameOverride` to validate it.

2025-03-10 13:50 UTC, nikola-jokic commented on charts/gha-runner-scale-set-controller/tests/template_test.go
> +}
Yeah, but then you move the logic into a test, and the test is basically a documentation of what is expected and how. If the test is too complicated, it is hard to see what is expected.
With the approach I suggested, you can clearly see the expected value when you override the namespace.
Other tests already cover no namespace override, so you cannot introduce a bug that will not be caught by the test suite. 

Since I forgot to add the deployment, that is just one test case more. Each file is written separately, so each file has a test case.

2025-03-11 13:27 UTC, fernandezcuesta commented on charts/gha-runner-scale-set-controller/tests/template_test.go
> +}
OK done, thanks for the help!

2025-03-18 20:40 UTC, nikola-jokic approved these changes
LGTM Thanks!

2025-03-18 20:41 UTC, merged