Optional override of runner image in chart
actions-runner-controller/actions-runner-controller pull request #666
Opened 2021-06-28 16:23 UTC by sledigabel

This commit adds the option to override the actions runner image. This
allows running the controller in environments where access to Dockerhub
is restricted.

It uses the parameter [--runner-image](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/main.go#L89) from the controller.
The default value is set as a constant
[here](https://github.com/actions-runner-controller/actions-runner-controller/blob/acb906164b6cc8b3604fa816cd3a99acffe991a2/main.go#L40).

The default value for the chart is the same.

2021-06-29 00:07 UTC, mumoshu requested changes
@sledigabel Hey! Thanks a lot for your contribution. This looks almost good 👍 The only thing I wanted was renaming `actionsRunner` to `actionsRunnerRepositoryAndTag` for consistency with the existing `dindSidecarRepositoryAndTag`. Would you mind confirming my proposed changes?

2021-06-29 00:07 UTC, mumoshu commented on charts/actions-runner-controller/templates/deployment.yaml
> +        - "--runner-image={{ .Values.image.actionsRunner }}"
```suggestion
        - "--runner-image={{ .Values.image.actionsRunnerRepositoryAndTag }}"
```

2021-06-29 00:07 UTC, mumoshu commented on charts/actions-runner-controller/values.yaml
> +  actionsRunner: "summerwind/actions-runner:latest"
```suggestion
  actionsRunnerRepositoryAndTag: "summerwind/actions-runner:latest"
```

2021-06-29 00:07 UTC, mumoshu commented on charts/actions-runner-controller/README.md
> +| `image.actionsRunner`                                    | The "repository/image" of the actions runner container                                                                     | summerwind/ac
```suggestion
| `image.actionsRunnerRepositoryAndTag `                   | The "repository/image" of the actions runner container                                                                     | summerwind/actions-runner:latest                                     |
```

2021-06-29 11:03 UTC, sledigabel commented
All updated, thanks for your review @mumoshu !

2021-06-30 00:42 UTC, mumoshu approved these changes
LGTM. Thanks a lot for the addition @sledigabel ☺️

2021-06-30 00:53 UTC, merged